### ISSUE TITLE
Problem with Environment Variable Keeps Resetting

### ISSUE THREAD

**Issue by PrathicSundararajan** [8go/pass-backup#1]
Thanks so much for this simple program.
I keep having to set the extensions variable to true each time I reopen my terminal. Every-time I reopen my terminal and try and do *"pass backup"*, I get the following: *"Error: backup is not in the password store"*.
By trying out *"printenv"* I see that the PASSWORD_STORE_ENABLE_EXTENSIONS is not listed. So I have to retype *"export PASSWORD_STORE_ENABLE_EXTENSIONS=true"* each time I open up the terminal if I do want to create a backup. I have tried all the steps so I am not quite sure what I am doing wrong or if we are meant to reset this variable each time we wish to create a backup. 
EDIT: Realized that if I added this to my .bash_profile, it would be preset every time I opened a new session. Thanks again for this program because it is quite useful.

**Comment by 8go** [comment]
@PrathicSundararajan 

Sorry, for the late response, but you figured it out already.

Yes, you are correct, the answer is to add this line

`export PASSWORD_STORE_ENABLE_EXTENSIONS=true`

into your `$HOME/.bashrc` or `$HOME/.bash_profile` file.

Thanks for using `pass-backup`
